version: '3'
services:
    # nginx container
    nginx:
        depends_on:
            - api
            - client
        build: ./nginx
        ports:
            - "3050:80"
    postgres:
        image: "postgres"
        environment:
            - POSTGRES_PASSWORD=postgres_password
    redis:
        image: "redis"
    api:
        image: arunsairajan/complex_api
        build: ./server
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432

    client:
        image: arunsairajan/complex_client
        build: ./client
    worker:
        image: arunsairajan/complex_worker
        build: ./worker
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379